# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sum_": "00_core.ipynb",
         "mean_": "00_core.ipynb",
         "variance": "00_core.ipynb",
         "std": "00_core.ipynb",
         "dot": "00_core.ipynb",
         "mat_vec_prod": "00_core.ipynb",
         "mat_mat_prod": "00_core.ipynb",
         "mse": "00_core.ipynb",
         "vec_mse": "00_core.ipynb",
         "linear_mse": "00_core.ipynb",
         "vec_linear_mse": "00_core.ipynb",
         "gradient": "00_core.ipynb",
         "vec_gradient": "00_core.ipynb",
         "predict_": "00_core.ipynb",
         "cost_elem_": "00_core.ipynb",
         "cost_": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://agelloz.github.io/42AI_machine_learning_bootcamp/"

git_url = "https://github.com/agelloz/42AI_machine_learning_bootcamp/tree/master/"

def custom_doc_links(name): return None
